
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import ProtectedRoute from '../../components/ProtectedRoute';

import { Inter } from "next/font/google";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ProtectedRoute>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ProtectedRoute>
  )
}
